
spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/contracts
      username: root
      password: 1234
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

file:
  directory:
        output: src/main/resources/output