spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3307/contracts_db?createDatabaseIfNotExist=true
    username: root
    password: toor
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# SFTP config
application:
  host: 0.0.0.0
  port: 2222
  user: user
  password: password123
  directory: /upload
