spring:
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:mysql://localhost:3307/contracts_db?createDatabaseIfNotExist=true
    username: root
    password: toor
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

# SFTP config
application:
  host: # 192.168....
  port: # ...
  user: # ...
  privateKey: # classpath:id_rsa
  directory: # /someDirectory
