version: "3.8"

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql_db_batch
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_PASSWORD: toor
    ports:
      - "3307:3306"
    expose:
      - 3307:3306

